### ISSUE TITLE
Inconsistency 6.2.4/6.2.2.

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/ISO19110#17]
Section 6.2.4.  "The feature catalogue shall also include, for each feature type, its feature operations ...." is inconsistent with 6.2.2 : "A feature catalogue should include definitions and descriptions of all feature types ..., including ..., and optionally including feature operations that are supported by the data."

**Comment by jetgeo** [comment]
I agree, these sentences must be harmonized.

**Comment by DaveDanko** [comment]
Changed the requirement in 6.2.4 in the  dd_smr document in dropbox adding "if they exist" i.e. : The feature catalogue SHALL include the feature operations, feature attributes, feature associations and roles associated with all feature types, if they exist.

**Comment by cdobrien** [comment]
Dave

If you have closed a number of issues, then I suggest you post a summary of what has been decided on the Live Link forum, or make a summary and send it to me so that I can make a WG6 N document. 

There are only 17 users of GitHub for all of the TC211 work. This is only part of the number of delegates registered to these projects. I can’t figure out who is registered to 19115-2 because the registration to GitHub seems to be for all the projects, and registration is by screen name. I only know some screen names, like “shorthair”. I don’t know who is missing.

You may think you have closed issues, but there may still be more input. If there is no more input, then good, but if there is input, then by discussing it now you avoid a future ballot comment.

Doug

**Comment by jetgeo** [comment]
Doug: This is the 19110 revision, not 19115-2. We are a small task force trying to finish the last few details from the EC work. These issues were originally discussed only by email, but I figured using GitHub was a better solution.
There is no need to collect input from others for this work.

**Comment by cdobrien** [comment]
Knut

Sorry wrong group.

Doug
